<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Payment Certificate</title>
  <link rel="stylesheet" href="<?php echo $variables['path'] . 'css/foundation.min.css'?>" />
  <link rel="stylesheet" href="<?php echo $variables['path'] . 'css/pv_print.css'?>" />
  <script src="<?php echo $variables['path'] . 'js/vendor/jquery.js'?>"></script>
  <script src="<?php echo $variables['path'] . 'js/vendor/modernizr.js'?>"></script>
</head>

<body>
    <a id="print-link" href="javascript:window.print()"><img src="<?php echo $variables['path'] . 'img/print.png';?>"/> &nbsp; Print this page</a>
  <!-- Top Line-->
  <div class="row small-12 top-logos">
    <img src="<?php echo $variables['path'] . 'img/ens-logo.png'?>" alt="ens-logo" />
    <img class="seal" src="<?php echo $variables['path'] . 'img/seal.png'?>" alt="enugu-seal" />
  </div>
  <!-- End Top Line-->

  <!-- Head-->
  <h1 class="page-title row small-12">
    PAYMENT CERTIFICATE
  </h1>

  <!-- PV main data-->
  <table class="main-data">
    <tbody>
      <tr>
        <th>Payment Being Made For</th>
        <td class="focus"><?php echo $variables['title']?></td>
      </tr>
      <tr>
        <th>Lot Number</th>
        <td class="focus"><?php echo $variables['lot_no']?></td>
      </tr>
      <tr>
        <th>Project Title</th>
        <td class="focus"><?php echo $variables['project_title']?></td>
      </tr>
      <tr>
        <th>Contractor Name</th>
        <td class="focus"><?php echo $variables['contractor_name']?></td>
      </tr>
      <tr>
        <th>Site Location</th>
        <td class="focus text-wrap"><?php echo $variables['site_location']?></td>
      </tr>
    </tbody>
  </table>
  <hr>
  <!-- FOOTER START -->
  <strong>PAYMENT SUMMARY</strong>
  <div class="print-prompt row">
    <table class="payment-summary cert">
      <tbody>
        <tr>
          <th>CONTRACT SUM:</th>
          <td>&#8358; </td>
          <td><?php echo $variables['contract_sum']?></td>
        </tr>
        <tr>
          <th>RETENTION(5%):</th>
          <td>&#8358; </td>
          <td><?php echo $variables['retention']?></td>
        </tr>
        <tr>
          <th>CONTRACT SUM LESS RETENTION:</th>
          <td>&#8358; </td>
          <td><?php echo $variables['less_retention']?></td>
        </tr>
        <tr>
          <th>VALUE OF WORKS DONE(<?php echo $variables['completion_status']?>%):</th>
          <td>&#8358; </td>
          <td><?php echo $variables['value_of_work']?></td>
        </tr>
        <tr>
          <th>LESS OF PREVIOUS CERTIFICATES(<?php echo $variables['percentage_prev']?>%):</th>
          <td>&#8358; </td>
          <td><?php echo $variables['value_prev']?></td>
        </tr>
        <tr class="tracking">
          <th>AMOUNT DUE NOW TO THE CONTRACTOR(Incl TAX):</th>
          <td>&#8358; </td>
          <td><?php echo $variables['amount_due']?></td>
        </tr>
      </tbody>
    </table>
    <div class="qr-code cert">
      <img class="qr-image" src="<?php echo 'https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=' . $variables['pc_number']?>" alt="QR-code">
      <div><strong><?php echo $variables['pc_number']?></strong></div>
      <div class="qr-footer">This Payment Certificate can be uniquely identified using this QR CODE</div>
    </div>
    <hr>
    <div class="disclaimer left">
      <p>
        <strong>Important Information</strong>
      </p>
      <p> The information in this document shall not be disclosed outside Enugu State Universal Basic Education Board and shall
        not be duplicated, used or disclosed in whole or in part for any purpose other than for the intended use.This information
        is auto-generated by The Enugu State Universal Basic Education Board Automated Project Management System. This is
        a sensitive document, any unauthorized use of this document would attract the appropriate consequences.</p>
    </div>
    <div class="disclaimer right">
      <p>
        <strong>Certificate</strong>
      </p>
      <p>
        It is certified that the above information is correct and was incurred under the relevant financial authority or other regulations
        quoted that services have been dully performed and that the rate/price charge is according to regulations/contract,
        fair and reasonable.
      </p>
    </div>
    <div class="disclaimer list">
      <p>
        <strong>Note</strong>
      </p>
      <p>
        <ul>
          <li>Finance Department would deduct all necessary taxes and VAT directly from the contractor money(s) before payment
          </li>
          <li>Retention monies are to placed in the retention deposit amount</li>
        </ul>
        </p>
    </div>
  </div>
</body>

</html>