<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Payment Certificate</title>
  <link rel="stylesheet" href="<?php echo $variables['path'] . 'css/foundation.min.css'?>" />
  <link rel="stylesheet" href="<?php echo $variables['path'] . 'css/pv_print.css'?>" />
  <script src="<?php echo $variables['path'] . 'js/vendor/jquery.js'?>"></script>
  <script src="<?php echo $variables['path'] . 'js/vendor/modernizr.js'?>"></script>
</head>

<body>
    <a id="print-link" href="javascript:window.print()"><img src="<?php echo $variables['path'] . 'img/print.png';?>"/> &nbsp; Print this page</a>
  <!-- Top Line-->
  <div class="row small-12 top-logos">
    <img src="<?php echo $variables['path'] . 'img/ens-logo.png'?>" alt="ens-logo" />
    <img class="seal" src="<?php echo $variables['path'] . 'img/seal.png'?>" alt="enugu-seal" />
  </div>
  <!-- End Top Line-->

  <!-- Head-->
  <h1 class="page-title row small-12">
    PAYMENT VOUCHER
  </h1>
  <!-- PV main data-->
  <table class="main-data">
    <tbody>
      <tr>
        <th>PV Num</th>
        <td class="focus"><?php echo $variables['pv_num']?></td>
      </tr>
      <tr>
        <th>Lot Number</th>
        <td class="focus"><?php echo $variables['lot_no']?></td>
      </tr>
      <tr>
        <th>Payment Type</th>
        <td class="focus"><?php echo $variables['payment_type']?></td>
      </tr>
      <tr>
        <th>Payee</th>
        <td class="focus"><?php echo $variables['payee']?></td>
      </tr>
      <tr>
        <th>Address</th>
        <td class="focus"><?php echo $variables['address']?></td>
      </tr>
      <tr>
        <th>Project Title</th>
        <td class="focus"><?php echo $variables['project_title']?></td>
      </tr>
      <tr>
        <th>Details</th>
        <td class="text-wrap"><?php echo $variables['details']?></td>
      </tr>
    </tbody>
  </table>
  <hr>
  <!-- FOOTER START -->
  <strong>PAYMENT SUMMARY</strong>
  <div class="print-prompt row">
    <table class="payment-summary">
      <tbody>
        <tr>
          <th>PAYMENT TYPE:</th>
          <td><?php echo strtoupper($variables['payment_type'])?></td>
        </tr>
        <tr>
          <th>PAYMENT AMOUNT:</th>
          <td>&#8358; <?php echo $variables['amount']?></td>
        </tr>
        <tr>
          <th>PAYMENT DATE:</th>
          <td><?php echo $variables['date_generated']?></td>
        </tr>
        <tr class="tracking">
          <th>PAYMENT TRACKING CODE:</th>
          <td><?php echo $variables['tracking_code']?></td>
        </tr>
      </tbody>
    </table>
    <div class="qr-code">
      <img class="qr-image" src="<?php echo 'https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=' . $variables['tracking_code']?>" alt="QR-code">
      <div><strong>PV:ENSUBEB/<?php echo $variables['tracking_code']?></strong></div>
      <div class="qr-footer">This Payment Voucher can be uniquely identified by this QR-CODE</div>
    </div>
    <hr>
    <div class="disclaimer left">
      <p>
        <strong>Important Information</strong>
      </p>
      <p> The information in this document shall not be disclosed outside Enugu State Universal Basic Education Board and shall
        not be duplicated, used or disclosed in whole or in part for any purpose other than for the intended use.This information
        is auto-generated by The Enugu State Universal Basic Education Board Automated Project Management System. This is
        a sensitive document, any unauthorized use of this document would attract the appropriate consequences.</p>
    </div>
    <div class="disclaimer right">
      <p>
        <strong>Certificate</strong>
      </p>
      <p>
        It is certified that the above information is correct and was incrred under the relevant financial authority or other regulations
        quoted that services have been dully performed and that the rate/price charge is according to regulations/contract,
        fair and reasonable.
      </p>
    </div>
  </div>
</body>

</html>